@echo off
cd /d "C:\Users\nicki\Desktop\Master websites\Drone Survey CR Copy 2026"
echo Removing stale git lock...
del /f ".git\index.lock" 2>nul
echo Running git add...
git add blog/drone-survey-central-valley-real-estate-costa-rica.html blog/index.html sitemap.xml
echo Committing...
git commit -m "Add Central Valley real estate/subdivision drone survey post (Cycle 3)"
echo Pushing to GitHub...
git push origin master
echo Done!
pause
